### ISSUE TITLE
SilverStripe 4 Compatibility

### ISSUE THREAD

**Issue by UndefinedOffset** [UndefinedOffset/silverstripe-markdown#13]
See #7, #8, #9, #10, #11, #12.

@robbieaverill I've opened this so we'll both get notifications on the subject. Per my comment on #12 have a look at the ss4-compat branch and let me know if it looks right. Still looks like we lost the history of the files but it may be something we can't avoid.

**Comment by robbieaverill** [comment]
Damn :( oh well.

**Comment by robbieaverill** [comment]
The composer alias needs to be changed to the new branch - #14

**Comment by UndefinedOffset** [comment]
merged, likely that branch will become the new master when 4 comes out but for now I'll leave it as it's own branch

**Comment by robbieaverill** [comment]
Looks good to me. Only a quick test with the default parser, but is working nicely.

**Comment by UndefinedOffset** [comment]
Cool I'll close this then, thanks again :)

**Comment by robbieaverill** [comment]
No worries. Would you be so kind as to tag an alpha version against the new branch?

**Comment by UndefinedOffset** [comment]
@robbieaverill tagged :)
